// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoAPI.DataAccess;

namespace TodoAPI.Migrations
{
    [DbContext(typeof(TodoDBContext))]
    [Migration("20221002050104_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TodoAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HomeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "rambukkana",
                            HomeNumber = "1",
                            Job = "Devoloper",
                            Name = "isuru",
                            Street = "Kegalle"
                        },
                        new
                        {
                            Id = 2,
                            City = "rambukkana",
                            HomeNumber = "1",
                            Job = "Engineer",
                            Name = "Alex",
                            Street = "Kegalle"
                        },
                        new
                        {
                            Id = 3,
                            City = "rambukkana",
                            HomeNumber = "1",
                            Job = "Doctor",
                            Name = "Ann",
                            Street = "Kegalle"
                        },
                        new
                        {
                            Id = 4,
                            City = "rambukkana",
                            HomeNumber = "1",
                            Job = "Designer",
                            Name = "Max",
                            Street = "Kegalle"
                        },
                        new
                        {
                            Id = 5,
                            City = "rambukkana",
                            HomeNumber = "1",
                            Job = "Nurse",
                            Name = "tony",
                            Street = "Kegalle"
                        },
                        new
                        {
                            Id = 6,
                            City = "rambukkana",
                            HomeNumber = "1",
                            Job = "Teacher",
                            Name = "liee",
                            Street = "Kegalle"
                        },
                        new
                        {
                            Id = 7,
                            City = "rambukkana",
                            HomeNumber = "1",
                            Job = "Trader",
                            Name = "las",
                            Street = "Kegalle"
                        },
                        new
                        {
                            Id = 8,
                            City = "rambukkana",
                            HomeNumber = "1",
                            Job = "Investor",
                            Name = "Bee",
                            Street = "Kegalle"
                        },
                        new
                        {
                            Id = 9,
                            City = "rambukkana",
                            HomeNumber = "1",
                            Job = "Banker",
                            Name = "mac",
                            Street = "Kegalle"
                        });
                });

            modelBuilder.Entity("TodoAPI.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2022, 10, 2, 10, 31, 4, 330, DateTimeKind.Local).AddTicks(7685),
                            Discription = "Drink 1 liter after workout",
                            Due = new DateTime(2022, 10, 2, 10, 31, 4, 331, DateTimeKind.Local).AddTicks(7683),
                            Status = 2,
                            Title = "Drink water"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Created = new DateTime(2022, 10, 2, 10, 31, 4, 331, DateTimeKind.Local).AddTicks(8366),
                            Discription = "Drink 1 liter after workout",
                            Due = new DateTime(2022, 10, 2, 10, 31, 4, 331, DateTimeKind.Local).AddTicks(8370),
                            Status = 2,
                            Title = "DMake Tea"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Created = new DateTime(2022, 10, 2, 10, 31, 4, 331, DateTimeKind.Local).AddTicks(8372),
                            Discription = "Drink 1 liter after workout",
                            Due = new DateTime(2022, 10, 2, 10, 31, 4, 331, DateTimeKind.Local).AddTicks(8373),
                            Status = 2,
                            Title = "Toilet"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Created = new DateTime(2022, 10, 2, 10, 31, 4, 331, DateTimeKind.Local).AddTicks(8374),
                            Discription = "Drink 1 liter after workout",
                            Due = new DateTime(2022, 10, 2, 10, 31, 4, 331, DateTimeKind.Local).AddTicks(8375),
                            Status = 2,
                            Title = "Brush Teeth"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Created = new DateTime(2022, 10, 2, 10, 31, 4, 331, DateTimeKind.Local).AddTicks(8377),
                            Discription = "Drink 1 liter after workout",
                            Due = new DateTime(2022, 10, 2, 10, 31, 4, 331, DateTimeKind.Local).AddTicks(8378),
                            Status = 2,
                            Title = "Breakfast"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            Created = new DateTime(2022, 10, 2, 10, 31, 4, 331, DateTimeKind.Local).AddTicks(8379),
                            Discription = "Drink 1 liter after workout",
                            Due = new DateTime(2022, 10, 2, 10, 31, 4, 331, DateTimeKind.Local).AddTicks(8380),
                            Status = 2,
                            Title = "Breakfast"
                        });
                });

            modelBuilder.Entity("TodoAPI.Models.Todo", b =>
                {
                    b.HasOne("TodoAPI.Models.Author", "Author")
                        .WithMany("Todos")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TodoAPI.Models.Author", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
